AWSTemplateFormatVersion: 2010-09-09
Description: 'First pratical of ec2 creation'
Resources:

    mynewSG:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: 'enable ssh acess by port 22'
            SecurityGroupIngress:
                CidrIp: '0.0.0.0/0'
                ToPort: 22
                FromPort: 22
                IpProtocol: 'tcp'
    microec2:
        Type: 'AWS::EC2::Instance'
        Properties:
            ImageId: 'ami-0e34e7b9ca0ace12d'
            AvailabilityZone: 'us-west-2a'
            InstanceType: 't2.micro'
            KeyName: 'gp_rep_key'
            SecurityGroupIds:
            -   !Ref mynewSG
    
